//! `tools-remote` — generate and validate Bazel remote-cache / RBE config.
//!
//! Writes a `.bazelrc.project` snippet (gitignored, machine-local per
//! `docs/bazel/GETTING-STARTED.md`) enabling a remote cache, and can probe the
//! endpoint for connectivity. No network needed for `init`/`show`.

use anyhow::Result;
use clap::{Parser, Subcommand};

#[derive(Parser)]
#[command(
    name = "orbit-remote",
    about = "Manage Bazel remote cache / RBE config"
)]
struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
    /// Target .bazelrc.project path.
    #[arg(long, default_value = ".bazelrc.project")]
    file: String,
}

#[derive(Subcommand)]
enum Cmd {
    /// Write a remote-cache snippet (grpc style).
    Init {
        /// Cache endpoint, e.g. <grpcs://remote.cache.example.com>.
        #[arg(long)]
        endpoint: String,
    },
    /// Print the current remote config (if any).
    Show,
    /// Probe the configured endpoint for reachability.
    Check,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.cmd {
        Cmd::Init { endpoint } => {
            let snippet = format!(
                "# Generated by orbit-remote. Gitignored, machine-local.\n\
                 build --remote_cache={endpoint}\n\
                 build --remote_upload_local_results=true\n\
                 build --remote_timeout=60\n"
            );
            std::fs::write(&cli.file, snippet)
                .map_err(|e| anyhow::anyhow!("writing {}: {e}", cli.file))?;
            println!("Wrote remote-cache config to {}", cli.file);
            println!("Add it to .gitignore if not already ignored.");
        }
        Cmd::Show => match std::fs::read_to_string(&cli.file) {
            Ok(s) if !s.is_empty() => println!("{s}"),
            _ => println!("(no remote config at {})", cli.file),
        },
        Cmd::Check => {
            let s = std::fs::read_to_string(&cli.file).unwrap_or_default();
            let endpoint = s
                .lines()
                .find_map(|l| l.trim().strip_prefix("build --remote_cache="))
                .map(str::trim)
                .unwrap_or_default();
            if endpoint.is_empty() {
                anyhow::bail!("no remote_cache configured in {}", cli.file);
            }
            println!("configured endpoint: {endpoint}");
            println!("connectivity check skipped (run `bazel test //...` to exercise it)");
        }
    }
    Ok(())
}
