//! `tools-codegen` — generate Rust boilerplate from names or JSON schemas.
//!
//! Subcommands:
//!   command NAME            emit a clap-derived command module skeleton
//!   struct  NAME --from F   emit a serde struct inferred from a JSON file
//!
//! Output goes to stdout unless `--out` is given.

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use std::path::PathBuf;

#[derive(Parser)]
#[command(name = "orbit-codegen", about = "Generate Rust boilerplate")]
struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
    /// Write to this file instead of stdout.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Subcommand)]
enum Cmd {
    /// Generate a clap command skeleton.
    Command { name: String },
    /// Generate a serde struct from a JSON sample.
    Struct {
        name: String,
        #[arg(long)]
        from: PathBuf,
    },
}

fn emit(out: Option<&PathBuf>, content: &str) -> Result<()> {
    if let Some(p) = out {
        std::fs::write(p, content).with_context(|| format!("writing {}", p.display()))
    } else {
        print!("{content}");
        Ok(())
    }
}

fn rust_type_of(v: &serde_json::Value) -> &'static str {
    match v {
        serde_json::Value::Null => "Option<serde_json::Value>",
        serde_json::Value::Bool(_) => "bool",
        serde_json::Value::Number(n) => {
            if n.is_i64() || n.is_u64() {
                "i64"
            } else {
                "f64"
            }
        }
        serde_json::Value::String(_) => "String",
        serde_json::Value::Array(_) => "Vec<serde_json::Value>",
        serde_json::Value::Object(_) => "serde_json::Value",
    }
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.cmd {
        Cmd::Command { name } => {
            let content = format!(
                r"//! Generated by orbit-codegen for command `{name}`.

use anyhow::Result;
use clap::Args;

#[derive(Args)]
pub struct {name}Args {{
    /// TODO: add flags.
    #[arg(long)]
    pub example: Option<String>,
}}

pub fn run(_args: {name}Args) -> Result<()> {{
    // TODO: implement {name}.
    Ok(())
}}
"
            );
            emit(cli.out.as_ref(), &content)?;
        }
        Cmd::Struct { name, from } => {
            let text = std::fs::read_to_string(&from)
                .with_context(|| format!("reading {}", from.display()))?;
            let value: serde_json::Value = serde_json::from_str(&text)
                .with_context(|| format!("parsing JSON in {}", from.display()))?;
            let obj = value
                .as_object()
                .context("top-level JSON must be an object")?;
            let mut fields = String::new();
            for (key, val) in obj {
                let line = format!("    pub {}: {},\n", key, rust_type_of(val));
                fields.push_str(&line);
            }
            let content = format!(
                r"//! Generated by orbit-codegen from {}.

use serde::{{Deserialize, Serialize}};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct {name} {{
{fields}}}
",
                from.display(),
            );
            emit(cli.out.as_ref(), &content)?;
        }
    }
    Ok(())
}
