apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orbit-workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orbit-server-state
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orbit-agent-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
