package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob(
        ["**/*.rs"],
        exclude = ["**/target/**"],
    ) + ["Cargo.toml"],
)

filegroup(
    name = "test_srcs",
    srcs = glob(["tests/**/*.rs"]),
)

sh_binary(
    name = "orbit-api",
    srcs = ["//tools:crate.sh"],
    args = [
        "orbit-api",
        "run",
    ],
)

sh_test(
    name = "test",
    srcs = ["//tools:crate.sh"],
    args = [
        "orbit-api",
        "test",
    ],
    tags = [
        "rust",
        "test",
    ],
)

sh_test(
    name = "fmt",
    srcs = ["//tools:crate.sh"],
    args = [
        "orbit-api",
        "fmt-check",
    ],
    tags = [
        "fmt",
        "rust",
    ],
)

sh_test(
    name = "lint",
    srcs = ["//tools:crate.sh"],
    args = [
        "orbit-api",
        "clippy",
    ],
    tags = [
        "lint",
        "rust",
    ],
)
