package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob(
        ["**/*.rs"],
        exclude = ["**/target/**"],
    ) + ["Cargo.toml"],
)

sh_test(
    name = "test",
    srcs = ["//tools:crate.sh"],
    args = [
        "orbit-agents",
        "test",
    ],
    tags = [
        "rust",
        "test",
    ],
)

sh_test(
    name = "fmt",
    srcs = ["//tools:crate.sh"],
    args = [
        "orbit-agents",
        "fmt-check",
    ],
    tags = [
        "fmt",
        "rust",
    ],
)

sh_test(
    name = "lint",
    srcs = ["//tools:crate.sh"],
    args = [
        "orbit-agents",
        "clippy",
    ],
    tags = [
        "lint",
        "rust",
    ],
)
