use orbit_events::render_typescript_bindings;

#[test]
fn contains_all_interface_definitions() {
    let bindings = render_typescript_bindings();
    let interfaces = [
        "OrbitGeneratedEventEnvelope",
        "OrbitGeneratedEventName",
        "OrbitGeneratedEventStatus",
        "OrbitGeneratedEventTopic",
        "OrbitGeneratedEventPayload",
        "OrbitGeneratedHostedTaskEventSummary",
        "OrbitGeneratedTaskRoutedEventPayload",
        "OrbitGeneratedLaneSignalEventPayload",
        "OrbitGeneratedApprovalRequestedEventPayload",
        "OrbitGeneratedApprovalResolvedEventPayload",
        "OrbitGeneratedTerminalEventPayload",
        "OrbitGeneratedConnectorInteractionRequest",
        "OrbitGeneratedConnectorInteractionResponse",
        "OrbitGeneratedConnectorEventRequest",
        "OrbitGeneratedConnectorEventPayload",
        "OrbitGeneratedAppliedOrphanPolicy",
    ];
    for interface in &interfaces {
        assert!(
            bindings.contains(interface),
            "bindings should contain `{interface}`"
        );
    }
}

#[test]
fn contains_all_event_names() {
    let bindings = render_typescript_bindings();
    let events = [
        "task.created",
        "task.routed",
        "task.cancelled",
        "lane.started",
        "lane.blocked",
        "lane.green",
        "lane.failed",
        "approval.requested",
        "approval.resolved",
        "memory.captured",
        "connector.event.received",
    ];
    for event in &events {
        assert!(
            bindings.contains(event),
            "bindings should contain event `{event}`"
        );
    }
}

#[test]
fn contains_all_event_statuses() {
    let bindings = render_typescript_bindings();
    let statuses = [
        "pending",
        "running",
        "blocked",
        "completed",
        "failed",
        "cancelled",
    ];
    for status in &statuses {
        assert!(
            bindings.contains(status),
            "bindings should contain status `{status}`"
        );
    }
}

#[test]
fn contains_all_event_topics() {
    let bindings = render_typescript_bindings();
    let topics = ["task", "lane", "approval", "memory", "connector"];
    for topic in &topics {
        assert!(
            bindings.contains(topic),
            "bindings should contain topic `{topic}`"
        );
    }
}

#[test]
fn contains_envelope_structure() {
    let bindings = render_typescript_bindings();
    assert!(bindings.contains("event: OrbitGeneratedEventName"));
    assert!(bindings.contains("status: OrbitGeneratedEventStatus"));
    assert!(bindings.contains("emittedAt: string"));
    assert!(bindings.contains("topic: OrbitGeneratedEventTopic"));
}

#[test]
fn contains_connector_event_payload_fields() {
    let bindings = render_typescript_bindings();
    assert!(bindings.contains("OrbitGeneratedConnectorInteractionRequest"));
    assert!(bindings.contains("action: string"));
    assert!(bindings.contains("blocks: Array<Record<string, unknown>>"));
    assert!(bindings.contains("data?: unknown"));
}

#[test]
fn contains_event_payload_combined_interface() {
    let bindings = render_typescript_bindings();
    // The combined interface exists
    assert!(
        bindings.contains("OrbitGeneratedEventPayload")
            || bindings.contains("OrbitGeneratedEventPayload")
    );
    assert!(bindings.contains("orphaned") || bindings.contains("task_status"));
}

#[test]
fn contains_generated_header() {
    let bindings = render_typescript_bindings();
    assert!(bindings.contains("generated by `cargo run"));
    assert!(bindings.contains("Do not edit by hand"));
}

#[test]
fn bindings_are_non_empty() {
    let bindings = render_typescript_bindings();
    assert!(!bindings.is_empty());
    assert!(bindings.lines().count() > 50);
}

#[test]
fn contains_lane_signal_event_payload_fields() {
    let bindings = render_typescript_bindings();
    assert!(bindings.contains("role?: string"));
    assert!(bindings.contains("description?: string"));
    assert!(bindings.contains("detail?: string"));
    assert!(bindings.contains("transport?: Record<string, unknown>"));
}

#[test]
fn contains_approval_payload_fields() {
    let bindings = render_typescript_bindings();
    assert!(bindings.contains("approval_kind?: string"));
    assert!(bindings.contains("action?: string"));
    assert!(bindings.contains("resolved_by?: string"));
}

#[test]
fn contains_terminal_payload_fields() {
    let bindings = render_typescript_bindings();
    assert!(bindings.contains("finish_reason?: string"));
    assert!(bindings.contains("tokens_output?: number"));
    assert!(bindings.contains("reconciled?: boolean"));
    assert!(bindings.contains("derived_state?: string"));
}

#[test]
fn contains_orphan_policy_fields() {
    let bindings = render_typescript_bindings();
    assert!(bindings.contains("approval_delay_secs: number"));
    assert!(bindings.contains("auto_retry_after_secs?: number"));
    assert!(bindings.contains("auto_cancel_after_secs?: number"));
}

#[test]
fn contains_hosted_task_summary_fields() {
    let bindings = render_typescript_bindings();
    assert!(bindings.contains("task_status?: string"));
    assert!(bindings.contains("pr_number?: number"));
    assert!(bindings.contains("pr_merged?: boolean"));
    assert!(bindings.contains("linear_issue_id?: string"));
    assert!(bindings.contains("graphite_stack_id?: string"));
    assert!(bindings.contains("execution_backend?: string"));
    assert!(bindings.contains("worker_status?: string"));
}
